[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][ValidateSet('Plan','Build')][string]$Action,
    [switch]$ConfirmMutation
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version 2.0
$CurrentRoot=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ProductRoot=Split-Path -Parent $CurrentRoot
$ProfilePath=Join-Path $PSScriptRoot 'profiles\AmazonBusiness.json'
$StateDir=Join-Path $ProductRoot 'CONNECTORS\AmazonBusiness\STATE'
$BuildStatePath=Join-Path $StateDir 'BUILD-STATE.json'
$VerifiedRoot=Join-Path $ProductRoot 'VERIFIED'
$TicketRunRoot='C:\Sandbox\Tickets\124261\PowerShell\runs'
$ExpectedSubscriptionId='8eb1dbee-a6f3-44b4-9df4-9766109f1ffa'
$ExpectedTenantId='3daa3943-d30e-43e4-a28d-04bd3216f019'
function Get-Sha256{param([string]$Path)(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant()}
function Write-JsonNoBom{param([string]$Path,$Object)$parent=Split-Path -Parent $Path;if(-not(Test-Path $parent)){New-Item -ItemType Directory -Force -Path $parent|Out-Null};[IO.File]::WriteAllText($Path,($Object|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)))}
function New-Run{$stamp=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ');$id='MCP-Lifecycle-Amazon-'+$Action+'-'+$stamp;$path=Join-Path $TicketRunRoot $id;New-Item -ItemType Directory -Force -Path $path|Out-Null;[pscustomobject]@{run_id=$id;run_path=$path}}
function Complete-Run{param($Run,$Result,[int]$ExitCode=0)$rp=Join-Path $Run.run_path 'result.json';$Result['result_json']=$rp;Write-JsonNoBom $rp $Result;$json=Get-Content -Raw $rp;Write-Host '===== BEGIN CABERLINK RESULT =====';Write-Host $json;Write-Host '===== END CABERLINK RESULT =====';Write-Host ('RESULT_JSON='+$rp);Write-Host ('VERDICT='+[string]$Result.verdict);Write-Host 'RAW_SECRET_VALUES_EXPORTED=false';exit $ExitCode}
function Resolve-AzureCliPython{$candidates=@('C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe');$az=Get-Command az.cmd -ErrorAction SilentlyContinue;if($az){$candidates+=Join-Path(Split-Path -Parent $az.Source)'python.exe'};foreach($c in $candidates|Select-Object -Unique){if(Test-Path $c -PathType Leaf){return $c}};throw 'Azure CLI bundled Python runtime was not found.'}
function ConvertTo-Arg{param([string]$Value)if($Value -notmatch '[\s"]'){return $Value};return '"'+($Value -replace '"','\"')+'"'}
function Invoke-Az{param([string[]]$Arguments,[switch]$AllowFailure)$py=Resolve-AzureCliPython;$oldEnc=$env:PYTHONIOENCODING;$oldUtf=$env:PYTHONUTF8;try{$env:PYTHONIOENCODING='utf-8';$env:PYTHONUTF8='1';$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$py;$all=@('-I','-B','-m','azure.cli')+$Arguments;$psi.Arguments=($all|ForEach-Object{ConvertTo-Arg ([string]$_)})-join ' ';$psi.UseShellExecute=$false;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.CreateNoWindow=$true;$proc=New-Object Diagnostics.Process;$proc.StartInfo=$psi;[void]$proc.Start();$stdout=$proc.StandardOutput.ReadToEnd();$stderr=$proc.StandardError.ReadToEnd();$proc.WaitForExit();$obj=[pscustomobject]@{exit_code=$proc.ExitCode;stdout=$stdout;stderr=$stderr};if($proc.ExitCode-ne 0-and-not$AllowFailure){throw ('Azure CLI failed exit '+$proc.ExitCode+': '+(($stderr -split "`r?`n"|Select-Object -Last 12)-join ' | '))};return $obj}finally{$env:PYTHONIOENCODING=$oldEnc;$env:PYTHONUTF8=$oldUtf}}
function Invoke-AzJson{param([string[]]$Arguments)$r=Invoke-Az ($Arguments+@('--output','json','--only-show-errors'));if([string]::IsNullOrWhiteSpace($r.stdout)){return $null};return $r.stdout|ConvertFrom-Json}
function Get-Profile{if(-not(Test-Path $ProfilePath)){throw 'Amazon profile missing.'};$p=Get-Content -Raw $ProfilePath|ConvertFrom-Json;if([string]$p.connector-ne'AmazonBusiness'){throw 'Amazon profile connector identity mismatch.'};return $p}
function Test-Source{param($Profile)if($Profile.build.enabled-ne$true){throw 'Amazon build profile not enabled.'};$root=[string]$Profile.build.canonical_source;$manifest=[string]$Profile.build.source_manifest;if(-not(Test-Path $root -PathType Container)){throw 'Amazon canonical source missing.'};if(-not(Test-Path $manifest -PathType Leaf)){throw 'Amazon source manifest missing.'};$mh=Get-Sha256 $manifest;if($mh-ne[string]$Profile.build.expected_source_manifest_sha256){throw ('Amazon source manifest drift. Expected '+[string]$Profile.build.expected_source_manifest_sha256+' got '+$mh)};$checks=@();foreach($e in @($Profile.build.expected_files)){$fp=Join-Path $root ([string]$e.name);$exists=Test-Path $fp -PathType Leaf;$actual=$(if($exists){Get-Sha256 $fp}else{$null});$checks+=[pscustomobject]@{name=[string]$e.name;exists=$exists;expected_sha256=[string]$e.sha256;actual_sha256=$actual;pass=($exists-and$actual-eq[string]$e.sha256)}};if(@($checks|Where-Object{-not$_.pass}).Count){throw 'Amazon canonical source file drift.'};[pscustomobject]@{source_root=$root;source_manifest=$manifest;source_manifest_sha256=$mh;file_checks=$checks}}
function Test-Azure{param($Profile)$acct=Invoke-AzJson @('account','show');if([string]$acct.id-ne$ExpectedSubscriptionId){throw 'Wrong Azure subscription.'};if([string]$acct.tenantId-ne$ExpectedTenantId){throw 'Wrong Azure tenant.'};$backend=@(Invoke-AzJson @('containerapp','list','--resource-group',[string]$Profile.proposed_resources.backend_resource_group));$tunnel=@(Invoke-AzJson @('containerapp','list','--resource-group',[string]$Profile.proposed_resources.tunnel_resource_group));if(@($backend|Where-Object{$_.name-eq[string]$Profile.proposed_resources.backend_app}).Count){throw 'Amazon backend name already exists; reconcile before build.'};if(@($tunnel|Where-Object{$_.name-eq[string]$Profile.proposed_resources.tunnel_app}).Count){throw 'Amazon tunnel name already exists; reconcile before build.'};[pscustomobject]@{subscription_id=[string]$acct.id;tenant_id=[string]$acct.tenantId;backend_absent=$true;tunnel_absent=$true}}
function Test-TagUnused{param([string]$Registry,[string]$Repository,[string]$Tag)$repos=@(Invoke-AzJson @('acr','repository','list','--name',$Registry));if($repos-notcontains$Repository){return $true};$tags=@(Invoke-AzJson @('acr','repository','show-tags','--name',$Registry,'--repository',$Repository));return($tags-notcontains$Tag)}
function Reconcile-Build{param([string]$Registry,[string]$Repository,[string]$Tag,[datetime]$Started,[datetime]$Ended)$img=Invoke-Az @('acr','repository','show','--name',$Registry,'--image',($Repository+':'+$Tag),'--output','json','--only-show-errors') -AllowFailure;if($img.exit_code-ne 0){return[pscustomobject]@{reconciled=$false;reason='tag_not_committed'}};$jo=$img.stdout|ConvertFrom-Json;$digest=[string]$jo.digest;if($digest-notmatch'^sha256:[0-9a-fA-F]{64}$'){return[pscustomobject]@{reconciled=$false;reason='invalid_digest'}};$runs=Invoke-Az @('acr','task','list-runs','--registry',$Registry,'--top','30','--output','json','--only-show-errors') -AllowFailure;if($runs.exit_code-ne 0){return[pscustomobject]@{reconciled=$false;reason='runs_unavailable';digest=$digest}};$arr=@($runs.stdout|ConvertFrom-Json);$ws=[datetimeoffset]$Started.ToUniversalTime().AddMinutes(-2);$we=[datetimeoffset]$Ended.ToUniversalTime().AddMinutes(2);$m=@($arr|Where-Object{try{$ct=[datetimeoffset]::Parse([string]$_.createTime);$_.status-eq'Succeeded'-and$ct-ge$ws-and$ct-le$we}catch{$false}});if($m.Count-ne 1){return[pscustomobject]@{reconciled=$false;reason=('successful_run_match_count_'+$m.Count);digest=$digest}};[pscustomobject]@{reconciled=$true;reason='exact_tag_digest_and_unique_successful_run_reconciled';digest=$digest.ToLowerInvariant();run_id=[string]$m[0].runId}}
function Save-Build{param($Profile,$Build,$Run)if(-not(Test-Path $StateDir)){New-Item -ItemType Directory -Force -Path $StateDir|Out-Null};if(Test-Path $BuildStatePath){throw 'Amazon BUILD-STATE already exists; duplicate build refused.'};$state=[ordered]@{schema='caberlink.mcp-lifecycle-manager.amazon-build-state.v1.5.1';ticket_id='124261';parent_ticket='122328';manager_version='1.5.1';run_id=$Run.run_id;verified_utc=(Get-Date).ToUniversalTime().ToString('o');source_manifest=[string]$Profile.build.source_manifest;source_manifest_sha256=[string]$Profile.build.expected_source_manifest_sha256;registry=[string]$Profile.build.registry;repository=[string]$Profile.build.repository;tag=[string]$Build.tag;image=[string]$Build.image;digest=[string]$Build.digest;acr_run_id=[string]$Build.acr_run_id;deployed=$false;raw_secret_values_exported=$false};Write-JsonNoBom $BuildStatePath $state;$stamp=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ');$snap=Join-Path $VerifiedRoot ($stamp+'\AMAZON-BUSINESS-BUILD-CERTIFICATION.json');Write-JsonNoBom $snap $state;(Get-Item $snap).IsReadOnly=$true;[pscustomobject]@{state_path=$BuildStatePath;state_sha256=Get-Sha256 $BuildStatePath;verified_snapshot=$snap}}
$run=New-Run
try{
    $profile=Get-Profile
    $source=Test-Source $profile
    if($Action-eq'Plan'){
        $exists=Test-Path $BuildStatePath -PathType Leaf
        $r=[ordered]@{schema='caberlink.mcp-lifecycle-manager.amazon-plan.v1.5.1';ticket_id='124261';run_id=$run.run_id;action='Plan';connector='AmazonBusiness';verdict=$(if($exists){'AMAZON_IMAGE_ALREADY_CERTIFIED'}else{'AMAZON_SOURCE_READY_FOR_IMMUTABLE_BUILD'});mutation_started=$false;source=$source;deployment_state=[string]$profile.deployment.state;next_bounded_action=$(if($exists){'AMAZON_CREDENTIALS_AND_ROLES_GATE_THEN_BACKEND_DEPLOYMENT_SUCCESSOR'}else{'RUN_TUNNEL_BUILD_AMAZONBUSINESS_PREFLIGHT'});raw_secret_values_exported=$false}
        Complete-Run $run $r 0
    }
    if(Test-Path $BuildStatePath -PathType Leaf){$s=Get-Content -Raw $BuildStatePath|ConvertFrom-Json;throw ('Amazon immutable image already certified; duplicate build refused. Digest='+[string]$s.digest)}
    $azure=Test-Azure $profile
    $registry=[string]$profile.build.registry;$repo=[string]$profile.build.repository
    $tag=[string]$profile.build.tag_prefix+'-'+(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ').ToLowerInvariant()
    if(-not(Test-TagUnused $registry $repo $tag)){throw 'Generated ACR tag already exists.'}
    $image=$registry+'.azurecr.io/'+$repo+':'+$tag
    if(-not$ConfirmMutation){$r=[ordered]@{schema='caberlink.mcp-lifecycle-manager.amazon-build-preflight.v1.5.1';ticket_id='124261';run_id=$run.run_id;action='Build';connector='AmazonBusiness';mode='PREFLIGHT_ONLY';target=$image;mutation_started=$false;mutation_committed=$false;pass=$true;verdict='AMAZON_IMMUTABLE_BUILD_PREFLIGHT_READY';source=$source;azure=$azure;rollback_or_readback='No mutation performed.';raw_secret_values_exported=$false};Complete-Run $run $r 0}
    $started=Get-Date
    $cap=Invoke-Az @('acr','build','--registry',$registry,'--image',($repo+':'+$tag),'--only-show-errors',[string]$source.source_root) -AllowFailure
    $ended=Get-Date
    $rec=$null
    if($cap.exit_code-ne 0){$rec=Reconcile-Build $registry $repo $tag $started $ended;if(-not$rec.reconciled){$r=[ordered]@{schema='caberlink.mcp-lifecycle-manager.amazon-build.v1.5.1';ticket_id='124261';run_id=$run.run_id;connector='AmazonBusiness';mutation_started=$true;mutation_committed=$false;pass=$false;verdict='SAFE_STOP_AMAZON_ACR_BUILD_FAILED';reconciliation=$rec;raw_secret_values_exported=$false};Complete-Run $run $r 6};$digest=[string]$rec.digest;$acrRunId=[string]$rec.run_id}else{$info=Invoke-AzJson @('acr','repository','show','--name',$registry,'--image',($repo+':'+$tag));$digest=[string]$info.digest;$acrRunId=$null}
    if($digest-notmatch'^sha256:[0-9a-fA-F]{64}$'){throw 'Built Amazon image digest missing or invalid.'}
    $build=[pscustomobject]@{tag=$tag;image=$image;digest=$digest.ToLowerInvariant();acr_run_id=$acrRunId}
    $state=Save-Build $profile $build $run
    $r=[ordered]@{schema='caberlink.mcp-lifecycle-manager.amazon-build.v1.5.1';ticket_id='124261';run_id=$run.run_id;connector='AmazonBusiness';mode='ACR_BUILD_NO_DEPLOYMENT';mutation_started=$true;mutation_committed=$true;changed=$true;pass=$true;verdict=$(if($cap.exit_code-eq 0){'AMAZON_IMMUTABLE_ACR_IMAGE_CERTIFIED_NO_DEPLOYMENT'}else{'AMAZON_IMMUTABLE_ACR_IMAGE_CERTIFIED_AFTER_CLIENT_RECONCILIATION'});source=$source;azure=$azure;image=$build;manager_state=$state;rollback_or_readback='No Container App deployment performed. Existing production connectors unchanged.';next_bounded_action='AMAZON_CREDENTIALS_AND_ROLES_GATE_THEN_MANAGER_BACKEND_DEPLOYMENT_EXTENSION';raw_secret_values_exported=$false}
    Complete-Run $run $r 0
}catch{
    $r=[ordered]@{schema='caberlink.mcp-lifecycle-manager.amazon-failure.v1.5.1';ticket_id='124261';run_id=$run.run_id;connector='AmazonBusiness';mutation_started=$false;pass=$false;verdict='SAFE_STOP_AMAZON_LIFECYCLE_FAILURE';error=$_.Exception.Message;raw_secret_values_exported=$false}
    Complete-Run $run $r 9
}
